version: "3.8"
services:
  jupyterlab:
    image: jupyter/datascience-notebook:latest
    stdin_open: true
    tty: true
    container_name: ${COMPOSE_PROJECT_NAME}
    labels:
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.rule=Host(`${COMPOSE_PROJECT_NAME}.energietransitiewindesheim.nl`)
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls=true
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.tls.certresolver=lets-encrypt
      - traefik.http.routers.${COMPOSE_PROJECT_NAME}.middlewares=private-network-ipwhitelist-${COMPOSE_PROJECT_NAME}
      - traefik.http.middlewares.private-network-ipwhitelist-${COMPOSE_PROJECT_NAME}.ipwhitelist.sourcerange= $IP_Whitelist
    networks:
      - web
    environment:
      - TWOMES_DB_URL=${TWOMES_DB_URL}
      - JUPYTER_ENABLE_LAB=yes
    restart: unless-stopped
    volumes:
      - data:/home/jovyan
networks:
  web:
    external:
      name: web
volumes:
  data: {}
